cbuffer PerViewConstantBuffer_t : register(b15, space0)
{
    column_major float4x4 g_matWorldToProjection : packoffset(c0);
    column_major float4x4 g_matProjectionToWorld : packoffset(c4);
    column_major float4x4 g_matWorldToView       : packoffset(c8);
    column_major float4x4 g_matViewToProjection  : packoffset(c12);
    float4 g_vInvProjRow3 : packoffset(c16);
    float4 g_vClipPlane0 : packoffset(c17);
    float g_flToneMapScalarLinear : packoffset(c18.x);
    float g_flInvToneMapScalarLinear : packoffset(c18.y);
    float g_fInvViewportZRange : packoffset(c18.z);
    float g_fMinViewportZScaled : packoffset(c18.w);
    float3 g_vCameraPositionWs;
    float g_flViewportMinZ ;
    float3 g_vCameraDirWs;
    float g_flViewportMaxZ;
    float3 g_vCameraUpDirWs;
    float g_flTime;
    float3 g_vDepthPsToVsConversion;
    float g_flNearPlane;
    float g_flFarPlane;
    float g_flLightBinnerFarPlane;
    float2 g_vInvViewportSize;
    float2 g_vViewportToGBufferRatio;
    float2 g_vMorphTextureAtlasSize;
    float4 g_vInvGBufferSize;
    float2 g_vViewportOffset;
    float2 g_vViewportSize;
    float2 g_vRenderTargetSize;
    float g_flFogBlendToBackground;
    float g_flHenyeyGreensteinCoeff;
    float3 g_vFogColor;
    float g_flNegFogStartOverFogRange;
    float g_flInvFogRange;
    float g_flFogMaxDensity;
    float g_flFogExponent;
    float g_flMod2xIdentity;
    int g_nMSAASampleCount;
    float g_flInvMSAASampleCount;
    uint g_tCompositeMorphAtlasTextureIndex;
    uint _pad0;
    float4 g_vFrameBufferCopyInvSizeAndUvScale;
    float4 g_vCameraAngles;
    float4 g_vWorldToCameraOffset : packoffset(c33);
    column_major float4x4 g_matPrevWorldToProjection;
    float4 g_vPrevWorldToCameraOffset;
    float4 g_vPerViewConstantExtraData0;
    float4 g_vPerViewConstantExtraData1;
    float4 g_vPerViewConstantExtraData2;
    float4 g_vPerViewConstantExtraData3;
};
